web:
  build: .
  restart: always
  expose:
    - "8080"
  environment:
    VIRTUAL_HOST: datasounds.case.beyond.codes
    LETSENCRYPT_HOST: datasounds.case.beyond.codes
    LETSENCRYPT_EMAIL: hi@beyond.codes
